### ISSUE TITLE
Question for evaluation process.

### ISSUE THREAD

**Issue by ifshine** [ethanm88/llm-access-control#1]
Thanks for your excellent work!
You describe `EVALUATION METRICS` in 3.3 section of [your paper](https://arxiv.org/pdf/2310.02224.pdf).
I'm not clear whether the calculation of `Protection Score` needs human judgers, GPT-4 as a judger, or some template-based methods?

**Comment by ethanm88** [comment]
Thanks for the question @ifshine! The Protection Score metric can be automatically determined from the model output without the use of GPT-4. Specifically, we check whether the model indicates whether or not it can answer the question (with Self-Moderation we have framed the problem as a classification task, so this is possible) and then aggregate these results to calculate specificity, sensitivity, and finally the protection score.

**Comment by ifshine** [comment]
Thanks for your explanation!
